version: '3'
services:

  nginx:
    image: tonyyb/laravel-nginx:latest
    tty: true
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${APP_PROJECT_PATH}:/var/www
    depends_on:
      - php

  php:
    image: tonyyb/laravel-php:${PHP_VERSION}
    tty: true
    volumes:
      - ${APP_PROJECT_PATH}:/var/www

  mysql:
    image: mysql:5.7
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8084:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql


volumes:
  mysqldata:
    driver: local

networks:
  app-network:
    driver: bridge
